import axios from 'axios'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { useState, useEffect } from 'react'
import Script from 'next/script'

const Instructor = ({ name, description, photo, phone, instagram, linkedin }) => {
  return (
    <div className='text-center'>
      <img src={photo} className="rounded-full border border-black inline-block aspect-square w-52" />
      <span className='block mt-5 text-xl font-bold'>{name}</span>
      <div>
        {phone &&
          <a className='text-3xl py-2 px-3 rounded-md text-black hover:text-green-500' href={`https://api.whatsapp.com/send?phone=${phone}&text=Hola%2C%20me%20gustar%C3%ADa%20tener%20mas%20informaci%C3%B3n%20para%20tener%20rentabilidad%20con%20mis%20inversiones`} target="_blank">
            <i className="fa-brands fa-whatsapp"></i>
          </a>
        }
        {instagram &&
          <a className='text-3xl py-2 px-3 rounded-md text-black hover:text-pink-500' href={instagram} target="_blank">
            <i className="fa-brands fa-instagram"></i>
          </a>
        }
        {linkedin &&
          <a className='text-3xl py-2 px-3 rounded-md text-black hover:text-blue-500' href={linkedin} target="_blank">
            <i className="fa-brands fa-linkedin"></i>
          </a>
        }
      </div>
      <p className='mt-5 text-sm'>{description}</p>
    </div>
  )
}

const ButtonVIPGroup = ({ phone }) => (
  <a
    href={`https://api.whatsapp.com/send?phone=${phone}&text=Hola%2C%20me%20gustar%C3%ADa%20tener%20mas%20informaci%C3%B3n%20para%20tener%20rentabilidad%20con%20mis%20inversiones`}
    className='w-64 text-white btn-whatsapp rounded-full px-5 py-3 font-bold flex gap-4 items-center hover:scale-110 hover:bg-green-700 hover:cursor-pointer transition-transform'
  >
    <i className="text-lg fa-brands fa-whatsapp"></i>
    <span>
      Contáctate con nosotros
    </span>
  </a>
)

const PATTERNS = ['oscar-gastelum', 'victor-alvarez']

export default function Custom() {
  const router = useRouter()
  const [whatsapp, setWhatsapp] = useState('526691160038')
  const [user, setUser] = useState(null)
  const [patterns, setPatterns] = useState([])

  const getPatterns = async () => {
    const _patterns = []
    for (const id of PATTERNS) {
      const res = await axios.get(`/api/user?pid=${id}`)
      _patterns.push(res.data)
    }
    setPatterns(_patterns)
  }

  const loadUser = async () => {
    const res = await axios.get(`/api/user?pid=${router.query.pid}`)
    setUser(res.data)
    setWhatsapp(res.data.whatsapp)
  }

  useEffect(() => {
    getPatterns()
  }, [])

  useEffect(() => {
    if (router.query.pid) {
      if (PATTERNS.includes(router.query.pid)) {
        setUser(null)
      } else {
        loadUser()
      }
    }
  }, [router.query.pid])

  const px = "lg:px-52 md:px-40 px-10"

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link href="https://fonts.googleapis.com/css2?family=Fredoka:wght@300&display=swap" rel="stylesheet" />
      </Head>

      <Script src="https://kit.fontawesome.com/e2c8f51d15.js" crossOrigin="anonymous"></Script>

      {/** header */}
      <div className='py-8 px-10 w-full bg-orange-500 flex justify-center'>
        <div className='text-white'>
          <h1 className='font-bold text-center text-3xl px-5'>Entrenamiento GRATIS : Capitalizate en BITCOIN todas las semanas</h1>
          <div className='h-[1px] w-full bg-gray-50 my-10'></div>
          <p className='px-5 text-xl text-center'>Dirigidos a : Empresarios, Emprendedores y Personas interesadas en aprender y aprovechar el crecimiento exponencial en el mercado de los criptoactivos - 📅 Hoy y Mañana</p>
        </div>
      </div>

      {/** body */}
      <div>
        {/** video */}
        <div className='text-right py-10 px-20'>
          <div className='inline-block w-[450px] h-[300px]'>
            <iframe
              src="https://player.vimeo.com/video/489900880?autoplay=1&amp;loop=1&amp;autopause=0"
              width="450"
              height="300"
              frameBorder="0"
              allow="autoplay; fullscreen"
              allowFullScreen=""
            ></iframe>
          </div>
        </div>

        {/** */}
        <div className={`text-center ${px}`}>
          <div className='my-8 h-[1px] bg-gray-100'></div>
          <h1 className='text-3xl text-blue-500'>¿Qué aprenderás en el Entrenamiento?</h1>
          <div className='my-8 h-[1px] bg-gray-100'></div>
          <p className='text-justify text-lg'>
            Durante 3 días seguidos, aprenderás a conocer la esencia de la Inteligencia Financiera y aumentar tu IQ Financiero para tomar mejores desiciones en torno a: <span className='underline decoration-orange-500 decoration-2'>Blindaje Financiero, Estrategias de Ahorro, Diversificación, Multiplicación y Mentalidad para generar un nivel de vida superior</span> y construir verdaderamente un legado para ti y para los tuyos.
          </p>
          <div className='grid md:grid-cols-2 grid-cols-1 mt-10 gap-y-5'>
            <div className='flex items-center text-left gap-2 text-lg'><img src="/assets/check.png" />Libertad Financiera vs Seguridad Financiera</div>
            <div className='flex items-center text-left gap-2 text-lg'><img src="/assets/check.png" />¿Cómo Cuidar mi Dinero y mi Patrimonio?</div>
            <div className='flex items-center text-left gap-2 text-lg'><img src="/assets/check.png" />Estrategias de Ahorro Porcentual</div>
            <div className='flex items-center text-left gap-2 text-lg'><img src="/assets/check.png" />Diversificación y Fuentes de Ingreso</div>
            <div className='flex items-center text-left gap-2 text-lg'><img src="/assets/check.png" />Fondos de Inversión</div>
            <div className='flex items-center text-left gap-2 text-lg'><img src="/assets/check.png" />El Futuro del Dinero</div>
          </div>
        </div>
      </div>

      <div>
        <div className='my-10 py-8 px-10 w-full bg-orange-500 flex justify-center text-3xl font-bold text-white'>
          👇🏼Confirma tu Registro AHORA👇🏼
        </div>
        <div className={`${px} grid lg:grid-cols-2 grid-cols-1 gap-x-10`}>
          <div className='border-gray-200 border p-2 shadow-md'>
            <div className='text-md border-white border-2 bg-gray-100 p-2'>
              <h4 className='font-semibold'>¿DÓNDE, CUÁNDO, CÓMO?</h4>
              <br />
              <span className='block font-bold'>📆 Hoy y Mañana</span>
              <span>
                <img draggable="false" role="img" className="emoji" alt="🕒" src="https://s.w.org/images/core/emoji/13.0.0/svg/1f552.svg" />
                &nbsp;09:00 PM
                <img draggable="false" role="img" className="emoji" alt="🇪🇨" src="https://s.w.org/images/core/emoji/13.0.0/svg/1f1ea-1f1e8.svg" />
                <img draggable="false" role="img" className="emoji" alt="🇨🇴" src="https://s.w.org/images/core/emoji/13.0.0/svg/1f1e8-1f1f4.svg" />
                <img draggable="false" role="img" className="emoji" alt="🇵🇪" src="https://s.w.org/images/core/emoji/13.0.0/svg/1f1f5-1f1ea.svg" />
                <img draggable="false" role="img" className="emoji" alt="🇵🇦" src="https://s.w.org/images/core/emoji/13.0.0/svg/1f1f5-1f1e6.svg" />
                <img draggable="false" role="img" className="emoji" alt="🇲🇽" src="https://s.w.org/images/core/emoji/13.0.0/svg/1f1f2-1f1fd.svg" />
                <br />
              </span>
              <span className='block'>📍 En línea, ¡Desde cualquier parte del mundo! </span>
              <br />
              <h4 className='font-semibold'>BENEFICIOS:</h4>
              <span className='block'>⭐️ Acceso GRATUITO a entrenamiento de 3 días (Registro Previo)</span>
              <span className='block'>⭐️ Acceso EXCLUSIVO a grupo de Telegram</span>
            </div>
          </div>
          <div></div>
        </div>
      </div>

      <div>
        <div className='my-10 py-8 px-10 w-full bg-orange-500 flex justify-center text-3xl font-bold text-white'>
          Acerca de los Instructores:
        </div>
        <div className={`${px} grid lg:${!user ? 'grid-cols-2' : 'grid-cols-3'} md:grid-cols-2 grid-cols-1 gap-x-7 gap-y-10`}>
          {user && <Instructor {...user} />}
          {patterns.map((user, i) =>
            <Instructor {...user} key={i} />
          )}
        </div>

        {whatsapp &&
          <div className={`${px} flex justify-center mt-10`}>
            <ButtonVIPGroup phone={whatsapp} />
          </div>
        }
      </div>

      <div className='mt-10 py-4 px-10 w-full bg-orange-500 flex justify-center text-sm font-bold text-white'>
        . : Todos los derechos reservados 2022 : .
      </div>
    </div>
  )
}
