import axios from 'axios'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { useState, useEffect } from 'react'

const Instructor = ({ name, description, photo }) => {
  return (
    <div className='text-center'>
      <img src={photo} className="rounded-full inline-block aspect-square w-52" />
      <span className='block mt-5 text-xl font-bold'>{name}</span>
      <p className='mt-5 text-sm'>{description}</p>
    </div>
  )
}

export default function Custom() {
  const router = useRouter()
  const [user, setUser] = useState(null)

  useEffect(() => {
    const load = async () => {
      const res = await axios.get(`/api/user?pid=${router.query.pid}`)
      setUser(res.data)
    }
    if (router.query.pid) {
      if (['oscar-gastelum'].includes(router.query.pid)) {
        setUser(null)
      } else {
        load()
      }
    }
  }, [router.query.pid])

  const px = "lg:px-52 md:px-40 px-10"

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link href="https://fonts.googleapis.com/css2?family=Fredoka:wght@300&display=swap" rel="stylesheet" />
      </Head>

      {/** header */}
      <div className='py-8 px-10 w-full bg-orange-500 flex justify-center'>
        <div className='text-white'>
          <h1 className='font-bold text-center text-3xl px-5'>Entrenamiento GRATIS : Capitalizate en BITCOIN todas las semanas</h1>
          <div className='h-[1px] w-full bg-gray-50 my-10'></div>
          <p className='px-5 text-xl text-center'>Dirigidos a : Empresarios, Emprendedores y Personas interesadas en aprender y aprovechar el crecimiento exponencial en el mercado de los criptoactivos - 📅 Hoy y Mañana</p>
        </div>
      </div>

      {/** body */}
      <div>
        {/** video */}
        <div className='text-right py-10 px-20'>
          <div className='inline-block w-[450px] h-[300px]'>
            <iframe
              src="https://player.vimeo.com/video/489900880?autoplay=1&amp;loop=1&amp;autopause=0"
              width="450"
              height="300"
              frameBorder="0"
              allow="autoplay; fullscreen"
              allowFullScreen=""
            ></iframe>
          </div>
        </div>

        {/** */}
        <div className={`text-center ${px}`}>
          <div className='my-8 h-[1px] bg-gray-100'></div>
          <h1 className='text-3xl text-blue-500'>¿Qué aprenderás en el Entrenamiento?</h1>
          <div className='my-8 h-[1px] bg-gray-100'></div>
          <p className='text-justify text-lg'>
            Durante 3 días seguidos, aprenderás a conocer la esencia de la Inteligencia Financiera y aumentar tu IQ Financiero para tomar mejores desiciones en torno a: <span className='underline decoration-orange-500 decoration-2'>Blindaje Financiero, Estrategias de Ahorro, Diversificación, Multiplicación y Mentalidad para generar un nivel de vida superior</span> y construir verdaderamente un legado para ti y para los tuyos.
          </p>
          <div className='grid md:grid-cols-2 grid-cols-1 mt-10 gap-y-5'>
            <div className='flex items-center text-left gap-2 text-lg'><img src="/assets/check.png" />Libertad Financiera vs Seguridad Financiera</div>
            <div className='flex items-center text-left gap-2 text-lg'><img src="/assets/check.png" />¿Cómo Cuidar mi Dinero y mi Patrimonio?</div>
            <div className='flex items-center text-left gap-2 text-lg'><img src="/assets/check.png" />Estrategias de Ahorro Porcentual</div>
            <div className='flex items-center text-left gap-2 text-lg'><img src="/assets/check.png" />Diversificación y Fuentes de Ingreso</div>
            <div className='flex items-center text-left gap-2 text-lg'><img src="/assets/check.png" />Fondos de Inversión</div>
            <div className='flex items-center text-left gap-2 text-lg'><img src="/assets/check.png" />El Futuro del Dinero</div>
          </div>
        </div>
      </div>

      <div>
        <div className='my-10 py-8 px-10 w-full bg-orange-500 flex justify-center text-3xl font-bold text-white'>
          👇🏼Confirma tu Registro AHORA👇🏼
        </div>
        <div className={`${px} grid lg:grid-cols-2 grid-cols-1 gap-x-10`}>
          <div className='border-gray-200 border p-2 shadow-md'>
            <div className='text-md border-white border-2 bg-gray-100 p-2'>
              <h4 className='font-semibold'>¿DÓNDE, CUÁNDO, CÓMO?</h4>
              <br />
              <span className='block'>📆 12, 13, 14 ENERO 2021</span>
              <span>
                <img draggable="false" role="img" className="emoji" alt="🕒" src="https://s.w.org/images/core/emoji/13.0.0/svg/1f552.svg" />
                10:00 AM
                <img draggable="false" role="img" className="emoji" alt="🇲🇽" src="https://s.w.org/images/core/emoji/13.0.0/svg/1f1f2-1f1fd.svg" />
                <img draggable="false" role="img" className="emoji" alt="🇬🇹" src="https://s.w.org/images/core/emoji/13.0.0/svg/1f1ec-1f1f9.svg" />
                <br />
                <img draggable="false" role="img" className="emoji" alt="🕒" src="https://s.w.org/images/core/emoji/13.0.0/svg/1f552.svg" />
                &nbsp;11:00 AM
                <img draggable="false" role="img" className="emoji" alt="🇪🇨" src="https://s.w.org/images/core/emoji/13.0.0/svg/1f1ea-1f1e8.svg" />
                <img draggable="false" role="img" className="emoji" alt="🇨🇴" src="https://s.w.org/images/core/emoji/13.0.0/svg/1f1e8-1f1f4.svg" />
                <img draggable="false" role="img" className="emoji" alt="🇵🇪" src="https://s.w.org/images/core/emoji/13.0.0/svg/1f1f5-1f1ea.svg" />
                <img draggable="false" role="img" className="emoji" alt="🇵🇦" src="https://s.w.org/images/core/emoji/13.0.0/svg/1f1f5-1f1e6.svg" />
                <br />
                <img draggable="false" role="img" className="emoji" alt="🕒" src="https://s.w.org/images/core/emoji/13.0.0/svg/1f552.svg" />
                01:00 PM
                <img draggable="false" role="img" className="emoji" alt="🇦🇷" src="https://s.w.org/images/core/emoji/13.0.0/svg/1f1e6-1f1f7.svg" />
                <img draggable="false" role="img" className="emoji" alt="🇺🇾" src="https://s.w.org/images/core/emoji/13.0.0/svg/1f1fa-1f1fe.svg" />
                <img draggable="false" role="img" className="emoji" alt="🇨🇱" src="https://s.w.org/images/core/emoji/13.0.0/svg/1f1e8-1f1f1.svg" />
                <br />
              </span>
              <span className='block'>📍 En línea, ¡Desde cualquier parte del mundo! </span>
              <br />
              <h4 className='font-semibold'>BENEFICIOS:</h4>
              <span className='block'>⭐️ Acceso GRATUITO a entrenamiento de 3 días (Registro Previo)</span>
              <span className='block'>⭐️ Acceso EXCLUSIVO a grupo de Telegram</span>
            </div>
          </div>
          <div></div>
        </div>
      </div>

      <div>
        <div className='my-10 py-8 px-10 w-full bg-orange-500 flex justify-center text-3xl font-bold text-white'>
          Acerca de los Instructores:
        </div>
        <div className={`${px} grid lg:grid-cols-3 md:grid-cols-2 grid-cols-1 gap-x-7 gap-y-10`}>
          {user && <Instructor name={user.name} photo={user.photo} description={user.description} />}
          <Instructor name="Oscar Gastelum" photo="/photos/oscar-gastelum.jpg" description={"Reconocido Empresario, Consultor y Conferencista Internacional, ha inspirado a cientos de Emprendedores y Ejecutivos en diferentes países de América, Europa y África."} />
          <Instructor name="Javier" photo="/photos/oscar-gastelum.jpg" description={"Reconocido Empresario, Consultor y Conferencista Internacional, ha inspirado a cientos de Emprendedores y Ejecutivos en diferentes países de América, Europa y África."} />
        </div>
      </div>

      <div className='mt-10 py-4 px-10 w-full bg-orange-500 flex justify-center text-sm font-bold text-white'>
        . : Todos los derechos reservados 2022 : .
      </div>
    </div>
  )
}
